chore: ease config accross machines

diff --git a/pywal/.local/bin/wal-switcher b/pywal/.local/bin/wal-switcher
--- a/pywal/.local/bin/wal-switcher
+++ b/pywal/.local/bin/wal-switcher
@@ -2,34 +2,22 @@
 
 # Fetch/change wallpaper and generate a colorscheme
 # Requirements: xrandr, curl, wal
+# TODO: Using maintained fork: https://github.com/eylles/pywal16
 # Credits to ilsenatorov for the idea
 # https://github.com/ilsenatorov/dotfiles/blob/big/rofi/themeswitch.sh
 
-set -xe
+# set -xe
+
+for i in wal wal-changer wall-dl; do
+    [ ! "$(command -v $i)" ] && { echo "Error: prerequisite $i not found in PATH" >&2 ; exit 1 ; }
+done
 
 PYWAL_BACKEND=${PYWAL_BACKEND:-wal}
 PYWAL_SCRIPT=~/.local/bin/wal-changer
 WALLPAPER_PATH=${XDG_PICTURES_DIR:-~/Pictures}/wallpapers
 mkdir -p "$WALLPAPER_PATH"
 
-_wal() {
-    wal --backend="$PYWAL_BACKEND" -o $PYWAL_SCRIPT -e -q -n "$@" > /dev/null
-
-    THEME=dark
-    # If the third argument (-l) is provided, this is a light theme
-    [ -n "$3" ] && THEME=light
-
-    # Store current theme to Xresources since there is no other way to know
-    # https://github.com/dylanaraps/pywal/issues/184
-    echo "*.theme: $THEME" >> "$XDG_CACHE_HOME"/wal/colors.Xresources
-}
-
-# Fetch a random wallpaper from unsplash
-_unsplash() {
-    RES=$(xrandr --nograb --current | awk '/\*/ {print $1}')
-    THEMES=static/unsplash
-    curl -o "$WALLPAPER_PATH/$THEMES" -J -L "https://source.unsplash.com/random/$RES" > /dev/null 2>&1
-}
+_wal() { wal --backend="$PYWAL_BACKEND" -o $PYWAL_SCRIPT -e -q -n "$@" > /dev/null; }
 
 # List user and core colorschemes
 _colorschemes() {
@@ -40,37 +28,29 @@ _colorschemes() {
 lstrip() { printf '%s\n' "${1##$2}"; }
 
 if [ -z "$@" ]; then
-    for o in unsplash theme/light theme/dark $(_colorschemes); do echo "$o"; done
+    for o in provider/unsplash theme/light theme/dark $(_colorschemes); do echo "$o"; done
     find -L "$WALLPAPER_PATH" -type f -printf '%P\n' | sort
 else
-    THEMES="$@"
+    SEL="$@"
 
-    case "$THEMES" in
-        unsplash) _unsplash ;;
+    case "$SEL" in
+        provider/*)
+            wall-dl "$(lstrip "$SEL" "provider/")"
+            rm -rf "$XDG_CACHE_HOME"/wal
+
+            # Sometimes process hangs while writing one of /dev/pts/{0,2,5}
+            # filtering the culprit fix the issue, but I don't know why this occurs.
+            # See: https://github.com/dylanaraps/pywal/issues/40
+            # Hotfix: pywal/sequences.py
+            # Writing to "/dev/pts/[0-9] lets you send data to open terminals.
+            # if to_send:
+            #     for term in glob.glob(tty_pattern):
+            #         if term != '/dev/pts/5':
+            #             util.save_file(sequences, term)
+            _wal -i "$WALLPAPER_PATH/today"
+        ;;
         theme/light) _wal -i "$WALLPAPER_PATH/today" -l ;;
         theme/dark) _wal -i "$WALLPAPER_PATH/today" ;;
-        colorscheme/*)
-            THEME=$(lstrip "$THEMES" "colorscheme/")
-            _wal --theme $THEME
-            ;;
+        colorscheme/*) _wal --theme "$(lstrip "$SEL" "colorscheme/")" ;;
     esac
-
-    [ -f "$WALLPAPER_PATH/$THEMES" ] && {
-        ln -sf "$WALLPAPER_PATH/$THEMES" "$WALLPAPER_PATH/today"
-
-        # Need to clear cache of previous colorschemes here
-        # Argument -c (Delete all cached colorschemes) does not work for me
-        rm -rf "$XDG_CACHE_HOME"/wal
-
-        # Sometimes process hangs while writing one of /dev/pts/{0,2,5}
-        # filtering the culprit fix the issue, but I don't know why this occurs.
-        # See: https://github.com/dylanaraps/pywal/issues/40
-        # Hotfix: pywal/sequences.py
-        # Writing to "/dev/pts/[0-9] lets you send data to open terminals.
-        # if to_send:
-        #     for term in glob.glob(tty_pattern):
-        #         if term != '/dev/pts/5':
-        #             util.save_file(sequences, term)
-        _wal -i "$WALLPAPER_PATH/$THEMES"
-    }
 fi
