bins: misc updates

diff --git a/bin/.local/bin/guncast b/bin/.local/bin/guncast
--- a/bin/.local/bin/guncast
+++ b/bin/.local/bin/guncast
@@ -4,29 +4,37 @@
 # Dependencies: hacksaw, ffmpeg
 # Credits: https://github.com/yayayayaka/bin/blob/f87f7696c76607460ed544a7f1b3410814b82bf2/record
 
+for i in hacksaw ffmpeg xclip; do
+    [ ! "$(command -v $i)" ] && {
+        echo "Required $i not found in PATH" >&2
+        exit 1
+    }
+done
+
+# Check prerequisites
 ### CONFIGURATION
 # Where you want your recordings to be stored
-DIR=${XDG_VIDEOS_DIR:-~/Videos}/record
+readonly DIR="${XDG_VIDEOS_DIR:-~/Videos}"/record
 # filename of the recording
 current=$(date +%F_%H-%M-%S)
 ###
 
 usage() {
-    cat <<EOL
-$(basename $0) - Record a selection of the screen with ffmpeg
+    cat << EOL
+$(basename "$0") - Record a selection of the screen with ffmpeg
 
 Usage:
- $(basename $0) [ -h | -a ]
+    $(basename "$0") [ -h | -a ]
 
 Options:
- -a, --with-audio Record a selection of the screen with audio
- -h, --help       Display this help message and quit
+    -a, --with-audio Record a selection of the screen with audio
+    -h, --help       Display this help message and quit
 EOL
     exit 0
 }
 
-_color() { xrdb -q | grep -m1 -i "$1" | cut -f2 ; }
-_h() { hacksaw -c "$(_color color4)" -g 2 -s 2 ; }
+_color() { xrdb -q | grep -m1 -i "$1" | cut -f2; }
+_h() { hacksaw -c "$(_color color4)" -g 2 -s 2; }
 
 record() {
     _h | {
@@ -75,14 +83,6 @@ record_with_audio() {
     }
     printf "%s" "$DIR/$current.mp4" | xclip -selection clipboard
 }
-
-# Check prerequisites
-for i in hacksaw ffmpeg xclip; do
-    if [ ! "$(command -v $i)" ]; then
-        echo "Error: prerequisite $i not found in PATH" >&2
-        exit 1
-    fi
-done
 
 mkdir -p "$DIR"
 
diff --git a/bin/.local/bin/gunshot b/bin/.local/bin/gunshot
--- a/bin/.local/bin/gunshot
+++ b/bin/.local/bin/gunshot
@@ -1,9 +1,12 @@
 #!/usr/bin/env sh
 
-# Take a screenshot from current window/screen or select a region.
+# Take a screenshot from current window/screen or a selected region.
 
 for i in shotgun hacksaw xdotool notify-send xrdb xclip; do
-    [ ! "$(command -v $i)" ] && { echo "Error: prerequisite $i not found in PATH" >&2 ; exit 1 ; }
+    [ ! "$(command -v $i)" ] && {
+        echo "Required $i not found in PATH" >&2
+        exit 1
+    }
 done
 
 SCREENSHOT_PATH=${XDG_PICTURES_DIR:-~/Pictures}/screenshots
@@ -11,7 +14,7 @@ SP="$SCREENSHOT_PATH/$(date +%s)-$1.png"
 
 _notify() { notify-send -i camera-photo "Screenshot :: $1" "Copied to $2"; }
 _color() { xrdb -q | grep -m1 -i "$1" | cut -f2; }
-_hacksaw() { hacksaw -c "$(_color color4)" -g 2 -s 2 -f "-i %i -g %g" || exit 1 ; }
+_hacksaw() { hacksaw -c "$(_color color4)" -g 2 -s 2 -f "-i %i -g %g" || exit 1; }
 
 mkdir -p "$SCREENSHOT_PATH"
 
diff --git a/bin/.local/bin/lockscreen b/bin/.local/bin/lockscreen
--- a/bin/.local/bin/lockscreen
+++ b/bin/.local/bin/lockscreen
@@ -1,48 +1,42 @@
 #!/usr/bin/env sh
 
-# Locks your screen using either a pixelated or corrupted screenshot.
-
-# Exit immediately if a command exits with a non-zero status.
 set -e
 
-# Check for dependency programs
-command -v i3lock >/dev/null || (echo "Please install i3lock." && exit 1)
-command -v scrot >/dev/null || (echo "Please install scrot." && exit 1)
+for i in convert corrupter i3lock scrot xset xrandr; do
+    [ ! "$(command -v $i)" ] && {
+        echo "Required $i not found in PATH" >&2
+        exit 1
+    }
+done
 
-# Check for conflicting xscreensaver process
-pgrep -x "xscreensaver" >/dev/null && (echo "xscreensaver detected. Please stop xscreensaver." && exit 1)
+prelock() {
+    pkill -USR1 dunst
+    xset +dpms dpms 5 5 5
+}
 
-# Check for arguments
-case "$1" in
-    --pixelated) EFFECT=pixelated;;
-    --corrupted) EFFECT=corrupted;;
-    *) EFFECT=pixelated;;
-esac
+lock() {
+    res=$(xrandr --nograb --current | awk '/\*/ {print $1}')
+    RANDOM=$(od -An -N2 < /dev/urandom)
 
-if [ $EFFECT = 'pixelated' ]; then command -v convert >/dev/null || (echo "Please install imagemagick." && exit 1)
-elif [ $EFFECT = 'corrupted' ]; then command -v corrupter >/dev/null || (echo "Please install corrupter (https://github.com/r00tman/corrupter)." && exit 1); fi
+    case "effect-$((RANDOM % 2))" in
+        "effect-0") scrot -q 50 - \
+                | corrupter -add 0 -mag -9 -bheight 25 -lr -12 -stride 9 -meanabber 0 -boffset -75 - \
+                | convert - RGB:- \
+                | i3lock -efn --raw $res:rgb -i /dev/stdin
+            ;;
+        "effect-1") scrot -q 50 - \
+                | convert -quality 1 -scale 10% -scale 1000% - RGB:- \
+                | i3lock -efn --raw $res:rgb -i /dev/stdin
+            ;;
+    esac
+}
 
-# get temp filenames
-t="$(mktemp).png"
-tm="${t}.mod"
-# make original screenshot
-scrot -q 50 "$t"
+postlock() {
+    pkill -USR2 dunst
+    xset dpms 0 0 0
+}
+trap postlock HUP INT TERM
 
-case $EFFECT in
-    # make pixelated version of screenshot
-    'pixelated') convert -quality 1 -scale 10% -scale 1000% "$t" "$tm" ;;
-    # corrupted version of screenshot
-    'corrupted') corrupter -add 0 -mag -9 -bheight 25 -lr -12 -stride 9 -meanabber 0 -boffset -75 "$t" "$tm" ;;
-esac
-
-# remove original screenshot
-rm "$t"
-# Locking
-# -e is supported since i3lock 2.6 (will not validate empty passwords against PAM)
-# i3lock -u -e -i "$tm"
-i3lock -n -i "$tm"
-
-# remove pixelated screenshot
-rm "$tm"
-
-exit 0
+prelock
+lock
+postlock
diff --git a/bin/.local/bin/recordscreen b/bin/.local/bin/recordscreen
--- a/bin/.local/bin/recordscreen
+++ b/bin/.local/bin/recordscreen
@@ -1,11 +1,11 @@
 #!/usr/bin/env sh
 
 if ! command -v ffmpeg >/dev/null 2>&1; then
-    echo Missing ffmpeg, please install first.
+    echo "Required ffmpeg not found in PATH" >&2
     exit 1
 fi
 
-SCREEN_RES=$(xrandr -q --current | grep '*' | awk '{print$1}')
+RES=$(xrandr --nograb --current | awk '/\*/ {print $1}')
 DATE=$(date '+%Y-%m-%d-%H:%M:%S')
 VIDEO_PATH="$HOME/Videos"
 FILENAME="recording_$DATE.mkv"
@@ -16,7 +16,7 @@ echo "Ctrl-C to exit"
 ffmpeg \
     -loglevel panic \
     -f x11grab \
-    -s "$SCREEN_RES" \
+    -s "$RES" \
     -i :0.0 \
     -r 25 \
     -vcodec libx264 "$VIDEO_PATH/$FILENAME"
diff --git a/bin/.local/bin/wall-dl b/bin/.local/bin/wall-dl
--- a/bin/.local/bin/wall-dl
+++ b/bin/.local/bin/wall-dl
@@ -3,14 +3,19 @@
 # set -xe
 
 for i in curl xrandr; do
-    [ ! "$(command -v $i)" ] && { echo "Error: prerequisite $i not found in PATH" >&2 ; exit 1 ; }
+    [ ! "$(command -v $i)" ] && {
+        echo "Required $i not found in PATH" >&2
+        exit 1
+    }
 done
 
-if [ -z $1 ]; then echo "A provider is required. Possible value: [unsplash]" >&2; exit 1; fi
+if [ -z $1 ]; then
+    echo "Provider required. Possible value: [unsplash]" >&2
+    exit 1
+fi
 
 WALLPAPER_PATH=${XDG_PICTURES_DIR:-~/Pictures}/wallpapers
 mkdir -p "$WALLPAPER_PATH"
-
 
 _unsplash() {
     RES=$(xrandr --nograb --current | awk '/\*/ {print $1}')
