chore: update to Nerd Fonts 3 code points

diff --git a/bin/.local/bin/openweathermap b/bin/.local/bin/openweathermap
--- a/bin/.local/bin/openweathermap
+++ b/bin/.local/bin/openweathermap
@@ -1,48 +1,29 @@
 #!/usr/bin/env sh
 
-# Fork from https://github.com/addy-dclxvi/almighty-dotfiles/blob/master/.executor/weather
-# Did some cleanup, added emojis and managed openweather map credentials from env variable instead
+set -e
+
+# Get your own API key here https://openweathermap.org
+for i in APIKEY LAT LONG; do
+    [ -z "$OPENWEATHERMAP_$i" ] && {
+    echo "Environment variable $OPENWEATHERMAP_$i required" >&2
+    exit 1
+}
+done
 
 API_ENDPOINT=https://api.openweathermap.org/data/2.5
-# Get your own API key here https://openweathermap.org
-API_KEY=$OPENWEATHERMAP_APIKEY
-# Check on https://openweathermap.org/find
-CITY_LAT=$OPENWEATHERMAP_LAT
-CITY_LONG=$OPENWEATHERMAP_LONG
 SYMBOL_CELSIUS="˚C"
-WEATHER_URL="${API_ENDPOINT}/weather?lat=${CITY_LAT}&lon=${CITY_LONG}&appid=${API_KEY}&units=metric"
-
-case "$1" in
-    --icon|--icon-fa5) OWM_SUNNY= OWM_CLOUDY= OWM_RAINY= OWM_STORM= OWM_SNOW= OWM_FOG= OWM_MISC= ;;
-    --icon-fa4) OWM_SUNNY= OWM_CLOUDY= OWM_RAINY= OWM_STORM= OWM_SNOW= OWM_FOG= OWM_MISC= ;;
-    --icon-weather) OWM_SUNNY= OWM_CLOUDY= OWM_RAINY=歹 OWM_STORM=朗 OWM_SNOW=晴 OWM_FOG=敖 OWM_MISC= ;;
-    --emoji) OWM_SUNNY=☀ OWM_CLOUDY=☁ OWM_RAINY=🌧 OWM_STORM=🌩 OWM_SNOW=❄ OWM_FOG=🌫 OWM_MISC=🐳 ;;
-    --text) OWM_SUNNY="Clear" OWM_CLOUDY="Cloudy" OWM_RAINY="Rainy" OWM_STORM="Stormy" OWM_SNOW="Snowy" OWM_FOG="Foggy" OWM_MISC="?" ;;
-    *)
-        echo "Show current weather by fetching openweathermap API."
-        echo ""
-        echo "# Usage"
-        echo "$ openweathermap [--text|--icon|--emoji]"
-        echo ""
-        echo "# As a polybar module:"
-        echo "[module/openweathermap]"
-        echo "type = custom/script"
-        echo "interval = 30"
-        echo "exec = openweathermap --emoji"
-        exit
-    ;;
-esac
-
+WEATHER_URL="${API_ENDPOINT}/weather?lat=${OPENWEATHERMAP_LAT}&lon=${OPENWEATHERMAP_LONG}&appid=${OPENWEATHERMAP_APIKEY}&units=metric"
+OWM_SUNNY= OWM_CLOUDY=󰖐 OWM_RAINY=󰖖 OWM_STORM=󰖓 OWM_SNOW=󰖘 OWM_FOG=󰖑 OWM_MISC=
 WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
 WEATHER_MAIN=$(echo "${WEATHER_INFO}" | jq ".weather[0].main")
 WEATHER_TEMP=$(echo "${WEATHER_INFO}" | jq ".main.temp")
 
 case "${WEATHER_MAIN}" in
     *Snow*) echo "${OWM_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}" ;;
-    *Rain*|*Drizzle*) echo "${OWM_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}" ;;
+    *Rain* | *Drizzle*) echo "${OWM_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}" ;;
     *Cloud*) echo "${OWM_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}" ;;
     *Clear*) echo "${OWM_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}" ;;
-    *Fog*|*Mist*) echo "${OWM_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}" ;;
+    *Fog* | *Mist*) echo "${OWM_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}" ;;
     *Thunder*) echo "${OWM_STORM} ${WEATHER_TEMP}${SYMBOL_CELSIUS}" ;;
     *) echo "${OWM_MISC} ${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}" ;;
 esac
