gnupg: introduce config

diff --git a/gnupg/.local/bin/pinentry-switch b/gnupg/.local/bin/pinentry-switch
--- a/gnupg/.local/bin/pinentry-switch
+++ b/gnupg/.local/bin/pinentry-switch
@@ -3,4 +3,9 @@
 case $PINENTRY_USER_DATA in
     tty) exec /usr/bin/pinentry-curses "$@" ;;
     rofi) exec "$HOME"/.local/bin/rofi/pinentry-rofi "$@" ;;
+    none)
+        echo "pinentry-switcher Error"
+        exit 1 # do not ask for passphrase
+        ;;
+    *) exec /usr/bin/pinentry "$@" ;;
 esac
