misc updates

diff --git a/@debian/.local/bin/wal-changer b/@debian/.local/bin/wal-changer
--- a/@debian/.local/bin/wal-changer
+++ b/@debian/.local/bin/wal-changer
@@ -5,26 +5,42 @@ reload_wallpaper() {
     # based on what is set as my wallpaper, this could either be a still picture
     # or a cinemagraph. Find out what it is, and launch with the appropriate program.
     WALL="$(cat "$XDG_CACHE_HOME"/wal/wal)"
-    MIMETYPE=$(file --mime-type -L "$WALL" | tr -d ' ' | awk -F: '{print $2}')
+    MIMETYPE=$(file --mime-type "$WALL" -bL)
     pkill -9 xwinwrap
+    pkill -9 paperview
     case "$MIMETYPE" in
     *png* | *jpg* | *jpeg*)
         # Set wallpaper with feh
         feh --no-fehbg --bg-fill "$WALL" &
         ;;
-    *gif* | *webm* | *mp4* | *mkv*)
-        # Play a video on the root window with xwinwrap/mpv
+    *gif*)
+        # Set gif with paperview, a high performance animated desktop background setter
+        GWF="$XDG_CACHE_HOME"/paperview
+        GFN="$(basename "$(readlink -f "$WALL")" .gif)"
+        command -v paperview >/dev/null 2>&1 || {
+            echo >&2 "Please install first paperview (https://github.com/glouw/paperview). Aborting."; exit 1;
+        }
+        mkdir -p "$GWF/$GFN"
+        if [ -n "$(find "$GWF/$GFN" -prune -empty 2>/dev/null)" ]; then
+            cp "$WALL" "$GWF/$GFN"
+            cd "$GWF/$GFN" || exit
+            convert -coalesce "$GFN".gif out.bmp
+            rm -f "$GFN".gif
+        fi
+        paperview "$GWF/$GFN" 5 &
+        ;;
+    *webm* | *mp4* | *mkv*)
+        # Play a video on the root window with xwinwrap + mpv
         # Credits: http://github.com/mitchweaver/bin
         # @TODO: Apparently we don't need anymore xwinwrap (https://github.com/mitchweaver/bin/commit/39eee9759525a702198ef783916454198e1e3e18)
         # @see: https://github.com/joshua-sterner/mpvbg/blob/master/mpvbg.sh
         command -v xwinwrap >/dev/null 2>&1 || {
-            echo >&2 "Please install first xwinwrap (https://github.com/ujjwal96/xwinwrap). Aborting."; exit 1;
+            echo >&2 "Please install first xwinwrap (https://github.com/Aaahh/xwinwrap). Aborting."; exit 1;
         }
         xwinwrap -ni -b -ov -ni -s -nf -fs -- \
             mpv --keepaspect=no --on-all-workspaces --no-config \
                 --no-input-default-bindings --no-stop-screensaver --loop-file \
                 --vd-lavc-fast --x11-bypass-compositor=no \
-                -x11-name=mpvbg \
                 --no-audio --no-osc --no-osd-bar -wid WID \
                 "$WALL"> /dev/null 2>&1 &
         ;;
@@ -71,9 +87,9 @@ reload_mpv() {
     mkdir -p "$PB_PATH"
     . "$XDG_CACHE_HOME"/wal/colors.sh
 
-    echo "default-style=\\\fnsans-serif\\\b1\\\bord0\\\shad0\\\fs20\\\c&H$(rgb_to_brg $color2)&\\\3c&H$(rgb_to_brg $color4)&
-bar-height-inactive=8
-bar-height-active=18
+    echo "default-style=\\\fnserif\\\bord0\\\shad0\\\fs20\\\c&H$(rgb_to_brg $color2)&\\\3c&H$(rgb_to_brg $color4)&
+bar-height-inactive=3
+bar-height-active=10
 bar-default-style=\\\bord0\\\shad0
 bar-foreground-style=
 bar-cache-style=\\\c&H$(rgb_to_brg $color2)&
@@ -96,9 +112,15 @@ reload_pywalfox() {
     echo "pywalfox end"
 }
 
+reload_zathura() {
+    mkdir -p "$XDG_CONFIG_HOME"/zathura
+    cat "$XDG_CACHE_HOME"/wal/zathurarc > "$XDG_CONFIG_HOME"/zathura/zathurarc
+}
+
 reload_wallpaper
 reload_sublime
 reload_kitty
 reload_pywalfox
 reload_mpv
 reload_dunst
+reload_zathura
